#!/usr/bin/env python3
"""Lift too-dark per-system brand colours so the nav accent stays legible.

The Platforms tab underline and the focused rail icon are tinted with the system's
${systemColor} (from the bundled system-metadata), and so is the neon hero's mood tint.
A few systems (e.g. pico-8) have very dark brand colours that vanish against the dark
chrome, and ES-DE cannot brighten a colour at runtime. This script scans every system's
colour and, for those below a legibility threshold, writes a section-accent override
(_inc/section-accent/<system>.xml) that raises ${systemColor}'s lightness while keeping
its hue/saturation. Because section-accent is included after the metadata, the lifted
colour flows to the underline, the focused icon and the hero tint together - one source,
consistent everywhere. Bright systems get no file and keep their colour untouched.

Run `python3 scripts/gen-dark-accent-overrides.py` to preview, add `--apply` to write.
Re-run after the metadata changes; it overwrites only the files it generates.
"""
import colorsys
import os
import sys
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
META = os.path.join(REPO, "steam-bigpicture-es-de", "system-metadata")
OUT = os.path.join(REPO, "steam-bigpicture-es-de", "_inc", "section-accent")

# Tunables. lum is perceived luminance 0..1; systems below LUM_THRESHOLD are "too dark".
LUM_THRESHOLD = 0.32
L_FLOOR = 0.58  # HSL lightness floor applied to dark systems (hue/saturation kept)

# Hand-authored section-accent files (the auto-collections) — never overwrite these.
RESERVED = {"auto-allgames", "auto-favorites", "auto-lastplayed"}

GENERATED_TAG = "GENERATED by scripts/gen-dark-accent-overrides.py - do not edit by hand"


def top_color(path):
    """Return the top-level <variables>/<systemColor> hex (no language blocks), or None."""
    block = ET.parse(path).getroot().find("variables")
    if block is None:
        return None
    el = block.find("systemColor")
    return (el.text or "").strip() if el is not None else None


def perceived_lum(r, g, b):
    return (0.299 * r + 0.587 * g + 0.114 * b) / 255.0


def brighten(hexstr):
    r, g, b = (int(hexstr[i:i + 2], 16) for i in (0, 2, 4))
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    r2, g2, b2 = colorsys.hls_to_rgb(h, max(l, L_FLOOR), s)
    return "%02x%02x%02x" % (round(r2 * 255), round(g2 * 255), round(b2 * 255))


def override_xml(system, bright_hex):
    return (
        f"<theme>\n"
        f"    <!-- {GENERATED_TAG}\n"
        f"         {system}: dark brand colour lifted so the nav underline, focused icon and hero\n"
        f"         tint stay legible. Overrides ${{systemColor}} after the metadata include. -->\n"
        f"    <variables>\n"
        f"        <systemColor>{bright_hex}</systemColor>\n"
        f"    </variables>\n"
        f"</theme>\n"
    )


def main():
    apply = "--apply" in sys.argv[1:]
    dark = []
    for fn in sorted(os.listdir(META)):
        if not fn.endswith(".xml") or fn.startswith("_"):
            continue
        system = fn[:-4]
        if system in RESERVED:
            continue
        color = top_color(os.path.join(META, fn))
        if not color or len(color) < 6:
            continue
        color = color[:6]
        try:
            r, g, b = (int(color[i:i + 2], 16) for i in (0, 2, 4))
        except ValueError:
            continue
        lum = perceived_lum(r, g, b)
        if lum >= LUM_THRESHOLD:
            continue
        dark.append((system, color, brighten(color), lum))

    for system, old, new, lum in dark:
        print(f"{system:20s} {old} -> {new}  (lum {lum:.3f})")
    print(f"\n{len(dark)} dark systems"
          f" (threshold lum < {LUM_THRESHOLD}, lightness floor {L_FLOOR})")

    if not apply:
        print("dry run - pass --apply to write the override files")
        return 0
    for system, old, new, lum in dark:
        with open(os.path.join(OUT, f"{system}.xml"), "w", encoding="utf-8") as f:
            f.write(override_xml(system, new))
    print(f"wrote {len(dark)} override files to _inc/section-accent/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
